### ISSUE TITLE
we miss you!

### ISSUE THREAD

**Issue by swyxio** [BuildingXwithJS/bxjs-weekly#130]
idk if you announced you were going on break or something, but just swinging by to say that i have always appreciated your work and hope you are okay.

**Comment by yamalight** [comment]
I have indeed announced a break (albeit only on youtube).
I am almost back and planning to build an AI (a bunch of classifiers really) to prepare podcasts for me since before I was doing all that manually.
So, stay tuned - they will be coming back in the nearest future 😅

**Comment by yamalight** [comment]
I'll close this, but feel free to re-open if there are any questions :)
