### ISSUE TITLE
Rename episodes with leading 0s

### ISSUE THREAD

**Issue by KevinColemanInc** [BuildingXwithJS/bxjs-weekly#2]
If you look at this view, the episodes are all out of order.  If you name the files like "001" for 1 and "012" for 12, then they would appear in the correct order.

https://github.com/BuildingXwithJS/bxjs-weekly/tree/master/episodes

**Comment by KevinColemanInc** [comment]
Maybe make a new folder?

**Comment by yamalight** [comment]
That'd also mean that current URLs change - which is something I want to evade 🤔

**Comment by KevinColemanInc** [comment]
You can leave the old folder and the content or just leave it with a link to the new location in each of the existing files?

Or create a new folder call "season 2" and just add better naming in that file.

**Comment by yamalight** [comment]
that doesn't really solve the problem in the long run though - just for the first 999 episodes (being a bit optimistic here) 🤔

**Comment by yamalight** [comment]
I like how that sounds 🤔 Could also have a folder split by years.
This + symlinks to "legacy" episodes could work quite well 🤔

**Comment by KevinColemanInc** [comment]
empty file with a text and link to the new location..  I have seen a few github projects do that.  github in generally is not very good at hosting web content like this

**Comment by yamalight** [comment]
So, it won't follow symlinks? Bleh, that's annoying 🤔 
File with a link might be a solution, yeah. Will dig around a bit more..

**Comment by yatki** [comment]
@yamalight symlinks work like a charm. see what we are doing here: https://github.com/LiskHQ/lisk-elements
